sonar.projectName = Python DSPAM
sonar.projectKey = python-dspam
sonar.python.version = 3.14
#sonar.sources = src, plugins
#sonar.tests = tests, plugins
sonar.inclusions = **/src/**
sonar.exclusions = **/tests/**
sonar.test.inclusions = **/tests/**
