# SPDX-License-Identifier: BSD-3-Clause


class DspamError(Exception): ...


class DspamPluginError(DspamError): ...


class DspamPluginNotFound(DspamPluginError): ...


class DspamParseError(DspamError): ...
