# SPDX-License-Identifier: BSD-3-Clause

name: Checks

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    name: Check code style
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6.0.3
    - uses: actions/setup-python@v6.2.0
      with:
          python-version-file: "pyproject.toml"
    - uses: pre-commit/action@v3.0.1

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6.0.3
    - uses: actions/setup-python@v6.2.0
      with:
          python-version-file: "pyproject.toml"
    - uses: astral-sh/setup-uv@v8.2.0
      with:
          activate-environment: true
    - run: uv sync --all-packages --frozen --group test
    - run: uv run pytest -v --cov --cov-report=xml
    - uses: actions/upload-artifact@v7.0.1
      with:
          path: coverage.xml
          name: coverage-report
